FROM node:16

WORKDIR /app

RUN npm install -g create-react-app \
                   create-react-native-app \
                   react-native-cli

# docker run -v ${PWD}:/app react-cli create-react-app myapp
