FROM node:16

WORKDIR /myapp

RUN npm install -g create-react-app \
                   create-react-native-app \
                   react-native-cli

# docker run -v ${PWD}:/app react-cli create-react-app myapp

# You have to add -it flag to create the JSON file.
# Rebuild the Dockerfile with the docker extensions
# and there, generate your node app.
