# This Docker Compose file creates the services MongoDB and your Node App.

version: '3.9'
services:
  mongo_service:
    container_name: mongo-container
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    env_file:
     - ./env-files/mongo-env.env

  node_service:
    container_name: node-todo-container
    build: ./
    volumes:
      - ./:/todo-app
    ports:
      - '8000:8000'
    env_file:
      - ./env-files/node-env.env
    depends_on:
      - mongo_service
